name: adam_fauzan_attendance_apps
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  intl: ^0.18.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  font_awesome_flutter: ^10.4.0
  flutter_iconly: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_form_builder: ^9.2.1
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^8.0.0
  flutter_widget_from_html: ^0.14.11
  form_builder_validators: 9.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  modal_progress_hud_nsn: ^0.5.1
  pull_to_refresh: ^2.0.0
  sizer: ^2.0.15
  table_calendar: ^3.0.9
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.4
  lottie: ^3.1.0
  awesome_notifications: ^0.8.2
  url_launcher: ^6.2.6
  pinput: ^3.0.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
