// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxYK_qPqTztB6YO2beVltWIrlLxzy7Kgk',
    appId: '1:85535538247:web:c7aae892d43045cf7d8562',
    messagingSenderId: '85535538247',
    projectId: 'attendance-app-adam',
    authDomain: 'attendance-app-adam.firebaseapp.com',
    storageBucket: 'attendance-app-adam.appspot.com',
    measurementId: 'G-NCM0S90BDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5tP6KGG6nXkMBnrrCQnaBirFhBVGTZnk',
    appId: '1:85535538247:android:0bb5e142a5b8776a7d8562',
    messagingSenderId: '85535538247',
    projectId: 'attendance-app-adam',
    storageBucket: 'attendance-app-adam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9mZA9nwUI6lpM_6RSIe5MsKHzgOihf0Q',
    appId: '1:85535538247:ios:8323962b049b69fa7d8562',
    messagingSenderId: '85535538247',
    projectId: 'attendance-app-adam',
    storageBucket: 'attendance-app-adam.appspot.com',
    iosBundleId: 'com.example.adamFauzanAttendanceApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9mZA9nwUI6lpM_6RSIe5MsKHzgOihf0Q',
    appId: '1:85535538247:ios:8323962b049b69fa7d8562',
    messagingSenderId: '85535538247',
    projectId: 'attendance-app-adam',
    storageBucket: 'attendance-app-adam.appspot.com',
    iosBundleId: 'com.example.adamFauzanAttendanceApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxYK_qPqTztB6YO2beVltWIrlLxzy7Kgk',
    appId: '1:85535538247:web:05784586a94eeec47d8562',
    messagingSenderId: '85535538247',
    projectId: 'attendance-app-adam',
    authDomain: 'attendance-app-adam.firebaseapp.com',
    storageBucket: 'attendance-app-adam.appspot.com',
    measurementId: 'G-1CKTDN8LGH',
  );
}
